### ISSUE TITLE
Error while creating function. 

### ISSUE THREAD

**Issue by ashishxooa** [bfansports/dynamodb-to-elasticsearch#11]
Hi, 

It seems some sequences in the makefile is wrong. I am getting the below error when trying to create the function. all the required Env are set and the env file is put in s3 as well.  

➜  dynamodb-to-elasticsearch git:(master) ✗ make create/dynamoToES DESC="Process DynamoDB stream to ES"
find build/ -mindepth 1 -not -name setup.cfg -delete
find: build/: No such file or directory
make: *** [build/setup.cfg] Error 1

**Comment by koxon** [comment]
Hello @ashishxooa . Create the folder and it should work.
You can create a .gitkeep file in the folder to make sure that even empty it is added to the repo by default and send me a pull request.
